package com.company.hr.enums;

public enum CandidateStage {
    PENDING_SCREENING,
    RESUME_REVIEW,
    HR_INTERVIEW,
    BUSINESS_INTERVIEW,
    FINAL_INTERVIEW,
    OFFER_APPROVAL,
    OFFER_SENT,
    ONBOARDED,
    RESUME_REJECTED,
    INTERVIEW_REJECTED,
    OFFER_REJECTED,
    ONBOARDING_ABANDONED
}
